import { Box, Button, HStack, Input } from "@chakra-ui/react";
import axios from "axios";
import { useFormik } from "formik";
import Head from "next/head";
import { useEffect } from "react";
import LsFiles from "../components/LsFiles";
import Nav from "../components/Nav";

export default function Home() {
  const formik = useFormik({
    initialValues: {
      path: "",
    },
    onSubmit: async (values) => {
      try {
        const { data } = await axios.post("/api/configure", values);
        formik.setValues({ ...data });
      } catch (err) {
        console.error(err);
      }
    },
    enableReinitialize: true,
  });

  const fetchConfig = async () => {
    try {
      const signal = axios.CancelToken.source();
      const { data } = await axios.get("/api/config", {
        cancelToken: signal.token,
      });
      formik.setValues({ ...data });
    } catch (err) {
      console.error(err);
    }
  };

  useEffect(() => {
    fetchConfig();
    return () => {};
  }, []);

  return (
    <Box className="p-4">
      <Head>
        <title>Workflow</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box>
        <Nav />
        <HStack>
          <Input
            placeholder="path"
            onChange={formik.handleChange("path")}
            value={formik.values.path}
          />
          <Button onClick={formik.submitForm}>save</Button>
        </HStack>
        {formik.values.path !== "" && (
          <LsFiles
            setPath={formik.setFieldValue as any}
            path={formik.values.path}
          />
        )}
      </Box>
    </Box>
  );
}
